# Generated by Django 4.1.4 on 2022-12-22 11:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, editable=False, upload_to=core.models.post_image_file_path),
        ),
    ]
